;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-slash
	c-indent-line-or-region
	hungry-delete-backward
	indent-for-tab-command
	org-return
	run-python
	sgml-slash
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	counsel-M-x
	electric-pair-delete-pair
	hungry-delete-forward
	org-self-insert-command
	suspend-frame
	))
